"""
test_folder_names.py
Checks that the folder names generated by the new taxonomy system match existing folders in parts/.
Currently validates countersunk (hex_head/black) and socket_cap (hex_head/black),
which are the two types that already have folders on disk.
Also validates bolt, set_screw, and nut against migration/parts/.
"""
import os
import sys

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from working_oomp_populate_bolt import generate as gen_bolt
from working_oomp_populate_set_screw import generate as gen_set_screw
from working_oomp_populate_nut import generate as gen_nut

try:
    from working_oomp_populate_countersunk import generate as gen_countersunk
    _has_countersunk = True
except ImportError:
    _has_countersunk = False

try:
    from working_oomp_populate_socket_cap import generate as gen_socket_cap
    _has_socket_cap = True
except ImportError:
    _has_socket_cap = False

PARTS_DIR = os.path.join(os.path.dirname(__file__), "..", "parts")
MIGRATION_PARTS_DIR = os.path.join(os.path.dirname(__file__), "..", "migration", "parts")
TAXONOMY_1 = "hardware"
TAXONOMY_2 = "screw"


def _build_folder_name(option):
    parts = [TAXONOMY_1, TAXONOMY_2]
    for key in ["taxonomy_3", "taxonomy_4", "taxonomy_5", "taxonomy_6", "taxonomy_7"]:
        val = option.get(key, "")
        if val:
            parts.append(val)
    return "_".join(parts)


def _existing_folders():
    return set(os.listdir(PARTS_DIR))


# ── countersunk hex_head black ────────────────────────────────────────────────

@pytest.mark.skipif(not _has_countersunk, reason="working_oomp_populate_countersunk not found")
class TestCountersunkHexHeadBlack:
    def setup_method(self):
        self.options = gen_countersunk()
        self.existing = _existing_folders()

    def test_all_generated_folders_exist_on_disk(self):
        missing = []
        for opt in self.options:
            name = _build_folder_name(opt)
            if name not in self.existing:
                missing.append(name)
        assert missing == [], f"Folders expected on disk but missing:\n" + "\n".join(missing)

    def test_no_extra_countersunk_hex_black_folders_on_disk(self):
        """Every countersunk_hex_head_black folder on disk should be generated."""
        prefix = f"{TAXONOMY_1}_{TAXONOMY_2}_countersunk_hex_head_black_"
        on_disk = {f for f in self.existing if f.startswith(prefix)}
        generated = {_build_folder_name(o) for o in self.options}
        extra = on_disk - generated
        assert extra == set(), f"Folders on disk not covered by generate():\n" + "\n".join(sorted(extra))


# ── socket_cap hex_head black ─────────────────────────────────────────────────

@pytest.mark.skipif(not _has_socket_cap, reason="working_oomp_populate_socket_cap not found")
class TestSocketCapHexHeadBlack:
    def setup_method(self):
        self.options = gen_socket_cap()
        self.existing = _existing_folders()

    def test_all_generated_folders_exist_on_disk(self):
        missing = []
        for opt in self.options:
            name = _build_folder_name(opt)
            if name not in self.existing:
                missing.append(name)
        assert missing == [], f"Folders expected on disk but missing:\n" + "\n".join(missing)

    def test_no_extra_socket_cap_hex_black_folders_on_disk(self):
        """Every socket_cap_hex_head_black folder on disk should be generated."""
        prefix = f"{TAXONOMY_1}_{TAXONOMY_2}_socket_cap_hex_head_black_"
        on_disk = {f for f in self.existing if f.startswith(prefix)}
        generated = {_build_folder_name(o) for o in self.options}
        extra = on_disk - generated
        assert extra == set(), f"Folders on disk not covered by generate():\n" + "\n".join(sorted(extra))


# ── cross-type duplicate check ────────────────────────────────────────────────

def test_no_cross_type_duplicates():
    """No two generators should produce the same folder name."""
    all_gens = []
    if _has_countersunk:
        all_gens.append(gen_countersunk)
    if _has_socket_cap:
        all_gens.append(gen_socket_cap)

    optional_modules = [
        "working_oomp_populate_countersunk_pozi",
        "working_oomp_populate_countersunk_philips",
        "working_oomp_populate_socket_cap_low_head",
        "working_oomp_populate_socket_cap_low_head_ultra",
        "working_oomp_populate_flat_head",
        "working_oomp_populate_button_head",
        "working_oomp_populate_grub",
        "working_oomp_populate_machine_screw",
        "working_oomp_populate_self_tapping",
        "working_oomp_populate_thread_forming",
        "working_oomp_populate_wood",
    ]
    import importlib
    for mod_name in optional_modules:
        try:
            mod = importlib.import_module(mod_name)
            all_gens.append(mod.generate)
        except ImportError:
            pass

    if not all_gens:
        pytest.skip("No screw generators available")
    

    seen = {}
    for gen in all_gens:
        for opt in gen():
            name = _build_folder_name(opt)
            assert name not in seen, (
                f"Duplicate folder name across generators: '{name}'\n"
                f"First seen from: {seen[name]}\n"
                f"Also produced by: {gen.__module__}"
            )
            seen[name] = gen.__module__


def _build_migration_folder_name(option, taxonomy_2):
    """Build folder name for types stored in migration/parts/."""
    parts = [TAXONOMY_1, taxonomy_2]
    for key in ["taxonomy_3", "taxonomy_4", "taxonomy_5", "taxonomy_6", "taxonomy_7"]:
        val = option.get(key, "")
        if val:
            parts.append(val)
    return "_".join(parts)


def _migration_folders():
    return set(os.listdir(MIGRATION_PARTS_DIR))


# ── bolt ──────────────────────────────────────────────────────────────────────

class TestBolt:
    def setup_method(self):
        self.options = gen_bolt()
        self.existing = _migration_folders()

    def test_all_generated_folders_exist_on_disk(self):
        missing = []
        for opt in self.options:
            name = _build_migration_folder_name(opt, "bolt")
            if name not in self.existing:
                missing.append(name)
        assert missing == [], "Folders expected in migration/parts/ but missing:\n" + "\n".join(missing)

    def test_no_extra_bolt_folders_on_disk(self):
        """Every hardware_bolt_* folder in migration/parts/ should be generated."""
        prefix = f"{TAXONOMY_1}_bolt_"
        on_disk = {f for f in self.existing if f.startswith(prefix)}
        generated = {_build_migration_folder_name(o, "bolt") for o in self.options}
        extra = on_disk - generated
        assert extra == set(), "Folders in migration/parts/ not covered by generate():\n" + "\n".join(sorted(extra))


# ── set_screw ─────────────────────────────────────────────────────────────────

class TestSetScrew:
    def setup_method(self):
        self.options = gen_set_screw()
        self.existing = _migration_folders()

    def test_all_generated_folders_exist_on_disk(self):
        missing = []
        for opt in self.options:
            name = _build_migration_folder_name(opt, "set_screw")
            if name not in self.existing:
                missing.append(name)
        assert missing == [], "Folders expected in migration/parts/ but missing:\n" + "\n".join(missing)

    def test_no_extra_set_screw_folders_on_disk(self):
        """Every hardware_set_screw_* folder in migration/parts/ should be generated."""
        prefix = f"{TAXONOMY_1}_set_screw_"
        on_disk = {f for f in self.existing if f.startswith(prefix)}
        generated = {_build_migration_folder_name(o, "set_screw") for o in self.options}
        extra = on_disk - generated
        assert extra == set(), "Folders in migration/parts/ not covered by generate():\n" + "\n".join(sorted(extra))


# ── nut ───────────────────────────────────────────────────────────────────────

class TestNut:
    def setup_method(self):
        self.options = gen_nut()
        self.existing = _migration_folders()

    def test_all_generated_folders_exist_on_disk(self):
        missing = []
        for opt in self.options:
            name = _build_migration_folder_name(opt, "nut")
            if name not in self.existing:
                missing.append(name)
        assert missing == [], "Folders expected in migration/parts/ but missing:\n" + "\n".join(missing)

    def test_no_extra_nut_folders_on_disk(self):
        """Every hardware_nut_* folder in migration/parts/ should be generated."""
        prefix = f"{TAXONOMY_1}_nut_"
        on_disk = {f for f in self.existing if f.startswith(prefix)}
        generated = {_build_migration_folder_name(o, "nut") for o in self.options}
        extra = on_disk - generated
        assert extra == set(), "Folders in migration/parts/ not covered by generate():\n" + "\n".join(sorted(extra))
